name: 'Arts & Technology '
favicon: null
layout_spectrum: 0.89492
typography_spectrum: 0.6846212409436703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.034630849957466125
  lightness: 0.8422205452807248
  saturation: 0.6921972485724837
  rhythmicContrast: 0.5212414101697505
purpose: []
